### ISSUE TITLE
No output on error

### ISSUE THREAD

**Issue by lara** [goby-lang/goby#809]
- Your operating system: `gobylang/goby:v0.1.11`
- How did you install Goby: Docker
- Goby version: `v0.1.11`
- The value of `$GOBY_ROOT`: `/go/src/github.com/goby-lang/goby`
- Error messages: None

I'm running `goby test.gb` which only contains `puts nil + 1` and it does not print any error message with `puts 1` it prints "1" ... I tried with `--verbose` and `DEBUG=1` but no output.

Works on `gobylang/goby:v0.1.10`.

**Comment by hachi8833** [comment]
Thank you for creating the issue!

Assumed you created your own `test.gb` with `puts nil + 1`.

I reproduced the issue with my own `test.gb` with the incorrect code with `goby test.gb` (Goby 0.11), while this works with the interaction mode (`goby -i`) as follows:

```ruby
Goby 0.1.11 😘 😆 😸
» puts nil + 1
#» NoMethodError: Undefined Method '+' for
```

FYI: Currently we have the following options for Goby.

> Usage of goby:
  -e	Generate reporting format
  -i	Run interactive goby
  -profile-cpu
    	Profile cpu usage
  -profile-mem
    	Profile memory allocation
  -v	Show current Goby version

@st0012 Can you see something else with this issue?

**Comment by st0012** [comment]
@lara thanks for reporting. I've tested it myself and it looks like the error was swallowed, I will check what's wrong.
